---
- name: Deploy Flask React CRUD Application
  hosts: production
  become: yes
  vars:
    app_dir: /opt/flask-react-crud
    docker_compose_version: "1.29.2"
  
  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - python3-pip
        state: present
        update_cache: yes
    
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    
    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'
    
    - name: Copy docker-compose file
      copy:
        src: ../docker-compose.prod.yml
        dest: "{{ app_dir }}/docker-compose.yml"
    
    - name: Copy environment file
      copy:
        src: ../.env.production
        dest: "{{ app_dir }}/.env"
    
    - name: Pull Docker images
      docker_compose:
        project_src: "{{ app_dir }}"
        pull: yes
    
    - name: Start containers
      docker_compose:
        project_src: "{{ app_dir }}"
        state: present
        restarted: yes
    
    - name: Ensure containers are running
      docker_compose:
        project_src: "{{ app_dir }}"
        state: started
